### ISSUE TITLE
Add Hong Kong & Taiwan please

### ISSUE THREAD

**Issue by fxfactorial** [stereobooster/react-simple-country-select#2]
{ "name": "Taiwan", "cca": "TW", "flag": "🇹🇼", "code": "" },
  { "name": "Hong Kong", "cca2": "HK", "flag": "🇭🇰", "code": "" },

thank you

**Comment by stereobooster** [comment]
Feel free to make PR https://github.com/stereobooster/react-simple-country-select/blob/master/src/countries.json

**Comment by fxfactorial** [comment]
I gave you the two lines to copy paste into the countries.json  and went through this issues because I didn't feel like the hassle of doing a PR. Can you just copy paste two those lines please and release a new version

**Comment by stereobooster** [comment]
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND...
>
> -- [LICENSE](https://github.com/stereobooster/react-simple-country-select/blob/master/LICENSE)
